version: '3.8'

services:
    express-app:
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - python-service
      volumes:
        - ./server:/app

    python-service:
       build:
        context: ./nlp-service
        dockerfile: Dockerfile
       ports:
        - "5000:5000"
       volumes:
        - ./nlp-service:/app
